name: Unit Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        node_version: [18, 20]
        operating_system: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.operating_system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node_version }}

      - name: install npm
        run: npm install

      - name: unit testing
        run: npm test


  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20

      - name: install npm
        run: npm install

      - name: unit testing
        run: npm run coverage

      - uses: actions/upload-artifact@v4
        if: failure() || success()
        with:
          name: code-coverage-result
          path: coverage
          retention-days: 5

